# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [8]:
%run initialise.py

ERROR:root:File `'initialise.py'` not found.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [9]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [10]:
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆)

In [22]:
def null_vec(n):
    return np.zeros(n)
null_vec(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [17]:
A = np.array([1,2,3,4,5,6])
#print("%d bytes" % (A.size * A.itemsize))
#or
print (8*len(A), 'bytes')

48 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [13]:
# %run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [24]:
def null_vec(n, k):
    a = np.zeros(n)
    a[k-1] = 1
    return a
null_vec(10, 5)

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [18]:
A = np.arange(10,50)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [21]:
def reverse_vec(v):
    v_rev = v[::-1]
    return v_rev
v = [1,2,3]
reverse_vec(v)

[3, 2, 1]

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [25]:
def matrix():
    lst = list(range(9))
    m = np.asarray(lst)
    m=m.reshape(3, -1)
    return m
matrix()

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [29]:
A = [1,2,0,0,4,0]
for i in range(len(A)):
  if A[i] == 0:
    print(i)

2
3
5


#### 11. Create a 3x3 identity matrix (★☆☆)

In [30]:
A = np.eye(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [137]:
A = np.random.uniform(0,15,(3,3,3))
print(A)

[[[ 2.91420768  8.19480607  2.69688271]
  [ 6.21215788 12.72447039 11.07557909]
  [11.64432695 10.20770548 11.50309985]]

 [[ 3.53685642  3.68742119  0.48298766]
  [ 2.20061481  5.81698838  0.94331413]
  [ 9.83390947  1.48317518 12.48344144]]

 [[10.02469134 12.83129305 14.44260676]
  [ 4.4729721  13.76376575  1.27433108]
  [ 7.77672728  9.83837653  1.63083194]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [138]:
A = np.random.uniform(0,15,100)
A = A.reshape(10,10)
print(A)
min = A[0][0]
max = A[0][0]
for i in range(len(A)):
  for j in range(len(A)):
    if A[i][j] > max:
      max = A[i][j]
    if A[i][j] < min:
      min = A[i][j]
print('Минимальное значение:', min, 'Максимальное значчение:', max)

[[ 9.64110628 10.23445014  2.33491621  5.18940829  6.19571636 11.9577761
   4.80103464 14.81178113  1.43454513  7.58114468]
 [ 2.68568443  2.32192846  6.25864498  1.45412791 14.8074825   1.92594679
  10.92333353 14.8440183  11.75176756  4.15479101]
 [ 9.9755932   9.57836734  4.72218952  2.50011844  2.15660071  3.10384234
   7.86398438  7.21033679  9.37060273 14.05628931]
 [10.50087511  9.04513813 11.73335332  9.08401927 11.38690859 10.82110385
  10.98825496  4.82959548  4.98468791  3.54737934]
 [11.57805626  4.995564   12.25707227 13.47318398 12.05938446 14.04045537
   0.09213371 11.3635983   6.10208797  6.84411906]
 [ 2.19486391 11.41683285  8.77048508  1.77886781 13.15166225  0.59403656
   8.12997318  2.38288198  9.11380426 13.71761432]
 [ 7.75252167  4.44666795  8.8563697   8.4353905   0.32210577 11.67968217
   1.40857019  1.32956095 10.80653629 10.0297536 ]
 [ 7.51347013 11.29195524 14.45680131 11.09028756 12.79160378  3.99741288
   2.66519781 10.00921055  5.89847027 11.37523922]
 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [140]:
A = np.random.uniform(0,15,30)
print(A)
print('Среднее значение:', A.mean())

[13.63343211  8.40957184  4.45867273  2.85955858  2.15641553  0.44733086
  7.17934158 11.59279776 14.62482695  9.0253148   6.71678227  6.94270114
 11.1658861   5.47342365  4.33902396  4.00100588  6.44474651  6.28080142
 10.79883995  5.63422358  2.036524    0.21217189 10.13275316 12.5575357
  9.5025381   7.54731759  5.23872397  3.09769695 14.60090612  5.54279821]
Среднее значение: 7.088455429020747


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [51]:
A = np.ones(100)
A = A.reshape(10,10)
A[1:-1,1:-1] = 0
print(A)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [142]:
A = np.ones(100)
A = A.reshape(10,10)
A = np.pad(A, pad_width=1, mode='constant', constant_values=0)
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [57]:
# узнаем, если выведем!
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [58]:
A = np.diag(1+np.arange(4),k=-1)
print(A)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [59]:
def checkerboard(w, b):
    """Создает матрицу по принципу шахматной доски.
    Parameters
    ----------
    w: Символ, обозначающий белую клетку
    b: Символ, обозначающий черную клетку
    
    Returns
    -------
    m: Матрица 8х8.
    """
    m = np.zeros(64)
    for i in range(64):
                if (i // 8 + i % 8) % 2 == 0:
                    m[i] = w
                else: 
                    m[i] = b
    m = m.reshape(8,8)
    return m
print(checkerboard(0, 1))

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [60]:
A = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [143]:
A = np.random.uniform(0,15,(5,5))
print(A)
A = (A - np.mean (A)) / (np.std (A))
print('Нормализованная:')
print(A)

[[14.26367599  1.52290056 14.94554442  5.2809117   9.61567814]
 [ 3.79626943  2.61767232 11.78247776  6.85405611 14.52075118]
 [11.14531963  7.8536724  12.70882216  3.36393996  4.79289573]
 [ 1.03879496  7.34690615 11.56856113  9.20353915  9.08140073]
 [13.71857093 10.14242262  9.96893949  4.97799231 12.55760708]]
Нормализованная:
[[ 1.36127572 -1.69385979  1.52478229 -0.79271893  0.24672321]
 [-1.14872421 -1.43134232  0.76630433 -0.41549155  1.42292028]
 [ 0.61351894 -0.1757916   0.98843427 -1.25239334 -0.90974124]
 [-1.80994441 -0.29731007  0.71500885  0.14789559  0.11860778]
 [ 1.23056391  0.3730323   0.33143244 -0.86535656  0.95217411]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [144]:
A = np.random.uniform(0,15,(5,3))
B = np.random.uniform(0,15,(3,2))
print(A)
print(B)
print(A.dot(B))

[[ 8.09239837  0.52540463  7.63441647]
 [12.36973776 14.01373434  1.6114716 ]
 [ 2.96044864 12.86300652 12.74380709]
 [ 0.65819713  0.22807092 14.23840872]
 [ 7.58635504 11.77085447 11.26139146]]
[[14.30671522  7.96393508]
 [ 1.28621774  4.12222358]
 [ 5.74612473 11.62050464]]
[[160.31973294 155.32894265]
 [204.25474593 175.00564773]
 [132.12642793 224.69047899]
 [ 91.52566022 171.63949316]
 [188.38506292 239.80238452]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [71]:
A = np.arange(11)
for i in range(4,8):
  A[i] = -A[i]
print(A)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [73]:
from numpy import *
print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [75]:
Z = [1,2,3]
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

TypeError: ignored

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [76]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-76-cd809174da5d>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-76-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

[5.83032278 0.02954594]
[0.97659132 0.44039509 0.39850697 0.64714765 0.78700136 0.49768797
 0.38386149 0.95488267 0.2830327  0.57081211]


#### 30. How to find common values between two arrays? (★☆☆)

In [82]:
A = [1,3,6,8,5,9,4,20,8,7,79]
B = [12,56,9,5,8,4,5,6]
#C = []
#for i in range(len(A)):
#  for j in range(len(B)):
#    if A[i] == B[j]:
#     print(A[i])
print(np.intersect1d(A,B))

[4 5 6 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [85]:
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [86]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-86-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [88]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2022-12-19 2022-12-20 2022-12-21


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [89]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [91]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [97]:
A = np.random.uniform(0,10,10)

print(A // 1)
print(np.floor(A))
print(A.astype(int))
print(np.trunc(A))

[8. 4. 0. 9. 9. 1. 6. 5. 9. 6.]
[8. 4. 0. 9. 9. 1. 6. 5. 9. 6.]
[8 4 0 9 9 1 6 5 9 6]
[8. 4. 0. 9. 9. 1. 6. 5. 9. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [98]:
A = np.zeros(25).reshape(5,5)
A += np.arange(5)
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [99]:
def generate():
    for i in range(10):
        yield i
A = np.fromiter(generate(),dtype=float,count=-1)
print(A)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [103]:
print(np.linspace(0,1,11,endpoint=False)[1:])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [145]:
A = np.random.uniform(0,15,10)
A.sort()
print(A)

[ 0.15854575  2.37260509  4.07050624  4.95321202  6.46222222  7.88992474
 11.75329374 12.80229908 14.06818701 14.58008796]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [146]:
A = np.random.uniform(0,15,10)
np.add.reduce(A)

89.5219432408239

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [151]:
A = np.random.uniform(0,15,5)
B = np.random.uniform(0,15,5)
print(A,B)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

[10.55435347 13.50511663 13.03107153 11.29981363  1.3264984 ] [14.20644589  0.42353995  0.8771643   1.47650285 10.86002171]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [152]:
A = np.random.uniform(0,15,(10,2))
X = A[:,0]
Y = A[:,1]
r = np.sqrt(X**2+Y**2)
phi = np.arctan2(Y,X)
print(r)
print(phi)

[18.58398894  8.44188394  8.45005674 12.82994108  6.26045551 12.85736428
 15.35068838  9.57410299 14.56418792  9.85604701]
[0.68988165 0.15169088 0.17427353 0.61359834 0.78428151 0.09839624
 1.06833581 0.92507008 0.69010006 1.40069479]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [153]:
A = np.random.uniform(0,15,10)
max = A[0]
print(A)
for i in range(len(A)):
  if A[i] > max:
      max = A[i]
      k = i
A[k] = 0
print(A)

[13.10741994  8.81968181  3.5842731   2.48713392  3.71129778 13.96714181
 13.23970151  8.27311828 12.71332016 10.24462975]
[13.10741994  8.81968181  3.5842731   2.48713392  3.71129778  0.
 13.23970151  8.27311828 12.71332016 10.24462975]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [113]:
A = np.zeros((5,5), [('x',float),('y',float)])
A['x'], A['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(A)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [116]:
X = np.arange(8)
Y = X + 1
for i in range(len(X)):
  for j in range(len(Y)):
    C[i][j] = 1.0 / (X[i]-Y[j])
print(C)

[[-1.         -0.5        -0.33333333 -0.25       -0.2        -0.16666667
  -0.14285714 -0.125     ]
 [        inf -1.         -0.5        -0.33333333 -0.25       -0.2
  -0.16666667 -0.14285714]
 [ 1.                 inf -1.         -0.5        -0.33333333 -0.25
  -0.2        -0.16666667]
 [ 0.5         1.                 inf -1.         -0.5        -0.33333333
  -0.25       -0.2       ]
 [ 0.33333333  0.5         1.                 inf -1.         -0.5
  -0.33333333 -0.25      ]
 [ 0.25        0.33333333  0.5         1.                 inf -1.
  -0.5        -0.33333333]
 [ 0.2         0.25        0.33333333  0.5         1.                 inf
  -1.         -0.5       ]
 [ 0.16666667  0.2         0.25        0.33333333  0.5         1.
          inf -1.        ]]


<ipython-input-116-38d6cc63b2b2>:5: RuntimeWarning: divide by zero encountered in true_divide
  C[i][j] = 1.0 / (X[i]-Y[j])


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [117]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [118]:
X = np.arange(8)
for i in range(len(X)):
  print(X[i])

0
1
2
3
4
5
6
7


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [119]:
A = np.arange(20)
v = np.random.uniform(0,15)
index = (np.abs(A-v)).argmin()
print(A[index])

16


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [155]:
A = (np.random.rand(10)*100).astype(np.float32)
Y = A.view(np.int32)
Y[:] = A
print(Y)

[70 55 25 92 64 69 25 29 27 58]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [122]:
s = '1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11'
A = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(A)

SyntaxError: ignored

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [123]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [124]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[-0.3155789  -0.31492936  0.35574647  0.34276732 -0.50840239 -0.15621384
  -0.22561839  0.2939114   0.3504922   0.17782547]
 [-0.34772295  0.49595743  0.46516881  0.08427895  0.3085622  -0.32813182
  -0.06433488 -0.34341686 -0.23162811 -0.03873277]
 [ 0.00209842  0.01805127 -0.24460455  0.31805579 -0.25748704  0.10372541
   0.02752975  0.06918214  0.28068476 -0.31723595]
 [ 0.60361768 -0.15792532 -0.15116505  0.13894602  0.22618782 -0.00492283
  -0.39116985 -0.0952463   0.01161465 -0.17993682]
 [-0.13508641 -0.29132233  0.30046057  0.22650876 -0.17260074  0.2057262
   0.35515705  0.13375294 -0.3091099  -0.31348614]]


#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

In [156]:
A = np.random.uniform(0,15,10)
x = 2
nearest = A.flat[np.abs(A - x).argmin()]
print(nearest)

0.13340401073386465


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [126]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [157]:
A = np.random.uniform(0,15,(5,5))
B = np.random.uniform(0,15,(5,5))
np.diag(np.dot(A, B))

array([214.83205875, 402.25916489, 191.44277148, 302.395017  ,
       185.98118169])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

In [159]:
A = np.random.uniform(0,2,(5,5))
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[1.8032803  1.86648152 1.16406291 1.97184185 1.61276056]
 [0.66297529 0.92435997 0.25812606 0.90839444 0.84646077]
 [0.70317851 0.92565433 1.41024285 1.95041263 1.00481659]
 [1.79749598 1.57772711 1.26408022 0.33584015 1.3145677 ]
 [0.79759491 1.17703436 1.86142449 1.41798455 1.56331805]]
[[0.66297529 0.92435997 0.25812606 0.90839444 0.84646077]
 [1.8032803  1.86648152 1.16406291 1.97184185 1.61276056]
 [0.70317851 0.92565433 1.41024285 1.95041263 1.00481659]
 [1.79749598 1.57772711 1.26408022 0.33584015 1.3145677 ]
 [0.79759491 1.17703436 1.86142449 1.41798455 1.56331805]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)